server:
  port: 8080
spring:
  application:
    name: "patient"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/patientdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 15s

#configration of actuator enpoint in eureka making info visible in eureka dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true




#info in eureka server dashboard
info:
  app:
    name: "patient"
    description: "Healthcare patient scoring Application"
    version: "1.0.0"

